site_name: Pretf Documentation
theme: readthedocs
docs_dir: docs
nav:
- Home: index.md
- Comparisons: comparisons.md
- Tutorial:
  - Get started: tutorial/get-started.md
  - Define resources: tutorial/define-resources.md
  - Dynamic resources: tutorial/dynamic-resources.md
  - Dynamic references: tutorial/dynamic-references.md
  - Custom workflows: tutorial/custom-workflows.md
  - Parameters: tutorial/parameters.md
  - Project structure: tutorial/project-structure.md
  - AWS projects: tutorial/aws-projects.md
- API:
  - pretf.api: api/api.md
  - pretf.aws: api/aws.md
  - pretf.log: api/log.md
  - pretf.run: api/run.md
  - pretf.util: api/util.md
