site_name: Pretf Documentation
theme: readthedocs
docs_dir: docs
nav:
- Home: index.md
- Comparisons: comparisons.md
- Tutorial:
  - Get started: tutorial/get-started.md
  - Define resources: tutorial/define-resources.md
  - Dynamic resources: tutorial/dynamic-resources.md
  - Dynamic references: tutorial/dynamic-references.md
  - Terraform variables: tutorial/terraform-variables.md
  - Custom workflows: tutorial/custom-workflows.md
  - Project structure: tutorial/project-structure.md
  - AWS projects: tutorial/aws-projects.md
  - direnv and asdf-vm: tutorial/direnv-and-asdf-vm.md
- API:
  - pretf.api: api/api.md
  - pretf.aws: api/aws.md
  - pretf.util: api/util.md
  - projects: api/projects.md
