#!/usr/bin/env python3

from pretf import aws, create_files, remove_files, terraform


aws.export_credentials(
    profile_name='customer-nonprod',
)

created_files = create_files(
    'src',
    envname='dev',
    envtype='nonprod',
    region='eu-west-1',
    data=[1, 2, 3],
)

remove_files('*.tf.json', exclude=created_files)

terraform.execute()
