#!/usr/bin/env python3

from pretf import aws, create, remove, terraform


aws.export_credentials(
    profile_name='customer-nonprod',
)

created = create(
    '../src',
    envname='dev',
    envtype='nonprod',
    region='eu-west-1',
    data=[1, 2, 3],
)

remove('*.tf.json', exclude=created)

terraform.execute()
