#!/usr/bin/env python3

from pretf import creates, remove, terraform, tf


@creates('iam.tf.json')
def create_resources(params):

    yield tf('provider.aws', {
        'region': params.aws_region,
    })

    group = yield tf('resource.aws_iam_group.admins', {
        'name': 'admins',
    })

    for username in params.users:

        user = yield tf(f'resource.aws_iam_user.{username}', {
            'name': username,
        })

        yield tf(f'resource.aws_iam_user_group_membership.{username}', {
            'user': user.name,
            'groups': [
                group.name,
            ],
        })


created_file = create_resources(
    aws_region='eu-west-1',
    users=['ray', 'violet'],
)

remove('*.tf.json', exclude=created_file)

terraform.execute()
