#!/usr/bin/env python3

from pretf import aws, create_files, run_terraform


# exports aws credentials for python and terraform to use
aws.export_credentials(
    profile_name='customer-nonprod',
)

# deletes pretf-*.json files
# searches specified directory for python files with @tf.file functions,
# calls them with kwargs as params argument,
# creates pretf-*.json file with the returned terraform config.
create_files(
    '../src',
    envname='dev',
    envtype='nonprod',
    region='eu-west-1',
    data=[1, 2, 3],
)

# executes terraform
run_terraform()
